// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZu5aQiSo7BwzJSlqUjzn_HtCgCtdI4Bw',
    appId: '1:102306664789:web:555224e6574ba10af4dfdc',
    messagingSenderId: '102306664789',
    projectId: 'statveil',
    authDomain: 'statveil.firebaseapp.com',
    storageBucket: 'statveil.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh_bbM7bZiHHFrtYSwM2383iar1kz_hIA',
    appId: '1:102306664789:android:15b6a229168d86b7f4dfdc',
    messagingSenderId: '102306664789',
    projectId: 'statveil',
    storageBucket: 'statveil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBidz06wLHl_kyfUEqJ_hYPZa3IKcgjHVg',
    appId: '1:102306664789:ios:3a3dacf48351babaf4dfdc',
    messagingSenderId: '102306664789',
    projectId: 'statveil',
    storageBucket: 'statveil.firebasestorage.app',
    iosBundleId: 'com.example.statveil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBidz06wLHl_kyfUEqJ_hYPZa3IKcgjHVg',
    appId: '1:102306664789:ios:3a3dacf48351babaf4dfdc',
    messagingSenderId: '102306664789',
    projectId: 'statveil',
    storageBucket: 'statveil.firebasestorage.app',
    iosBundleId: 'com.example.statveil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZu5aQiSo7BwzJSlqUjzn_HtCgCtdI4Bw',
    appId: '1:102306664789:web:922c3f09e1c2922df4dfdc',
    messagingSenderId: '102306664789',
    projectId: 'statveil',
    authDomain: 'statveil.firebaseapp.com',
    storageBucket: 'statveil.firebasestorage.app',
  );
}
